//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoneFinch.ReactiveExtensions.Wpf.MyWcfServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWcfServiceReference.IMyWcfService")]
    public interface IMyWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWcfService/GetCurrentDateTimeUtc", ReplyAction="http://tempuri.org/IMyWcfService/GetCurrentDateTimeUtcResponse")]
        System.DateTime GetCurrentDateTimeUtc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWcfService/GetCurrentDateTimeUtc", ReplyAction="http://tempuri.org/IMyWcfService/GetCurrentDateTimeUtcResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetCurrentDateTimeUtcAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyWcfServiceChannel : StoneFinch.ReactiveExtensions.Wpf.MyWcfServiceReference.IMyWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWcfServiceClient : System.ServiceModel.ClientBase<StoneFinch.ReactiveExtensions.Wpf.MyWcfServiceReference.IMyWcfService>, StoneFinch.ReactiveExtensions.Wpf.MyWcfServiceReference.IMyWcfService {
        
        public MyWcfServiceClient() {
        }
        
        public MyWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetCurrentDateTimeUtc() {
            return base.Channel.GetCurrentDateTimeUtc();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetCurrentDateTimeUtcAsync() {
            return base.Channel.GetCurrentDateTimeUtcAsync();
        }
    }
}
